name: referon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.11.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  otp_text_field: ^1.1.3
  responsive_framework: ^0.2.0
  easy_sidemenu: ^0.3.1
  
  step_progress_indicator: ^1.0.2
  enhance_stepper: ^0.1.1
  flutter_dash: ^1.0.0
  blinking_text: ^1.0.2
  weather_icons: ^3.0.0
  dropdown_search: ^5.0.2
  searchfield: ^0.6.9
  expandable_bottom_bar: ^2.0.2
  spincircle_bottom_bar: ^2.0.0
  carousel_slider: ^4.1.1
  carousel_pro: ^1.0.0
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.2
  form_builder: ^1.0.1
  flutter_form_builder: ^7.6.0
  phone_number: ^1.0.0
  group_radio_button: ^1.2.0
  http: ^0.13.5
  email_validator: ^2.1.17
  image_picker: ^0.8.5+3
  dropdownfield: ^1.0.3
  flutter_year_picker: ^0.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^11.0.1
  
  
  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logocircle.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splashimg.png
    - assets/images/logo.png
    - assets/images/loginheader.png
    - assets/images/carousel.jpg
    - assets/images/carouselvan.jpg
    - assets/images/carouseltruck.jpg
    - assets/images/logocircle.png
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
